version: '3.7'

services:
  fitdashboard-db:
    image: postgres:17.5
    env_file: .env
    ports:
      - 5434:5432
    networks:
      - fitdashboard-rede
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5


  django_fitdashboard:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file: .env
    environment:
      - DB_HOST=fitdashboard-db
      - DB_NAME=${POSTGRES_DB}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_USER=${POSTGRES_USER}
      - DB_PORT=${DB_PORT}
      - ACCESS_TIME=${ACCESS_TIME}
      - REFRESH_TIME=${REFRESH_TIME}
      - DEBUG=${DEBUG}

    ports:
      - 8002:8000
    volumes:
      - .:/fitDash
    depends_on:
      - fitdashboard-db
    networks:
      - fitdashboard-rede
    
    

networks:
  fitdashboard-rede:
    driver: bridge
